import { cvContent } from "./cv-content";

export const siteConfig = {
  name: "Matheus Nascimento",
  title: "Matheus Nascimento | Editor de Vídeo · eSports & Campanhas",
  description: cvContent.summary,
  url: "https://matheusnascimento.dev",
  locale: "pt_BR",
  email: "novikmovies@gmail.com",
  phone: "+5511953031803",
  phoneDisplay: "(11) 95303-1803",
  location: "São Paulo, SP",
  address: "Vila Granada, São Paulo - SP",
  age: 28,
  role: cvContent.role,
  keywords: [
    "editor de vídeo",
    "editor de vídeo São Paulo",
    "eSports",
    "W7M Esports",
    "Netflix",
    "Banco do Brasil",
    "iFood",
    "Mercado Livre",
    "Adobe Premiere Pro",
    "Adobe After Effects",
    "Adobe Photoshop",
    "Sony Vegas",
    "ElevenLabs",
    "ChatGPT",
    "YouTube",
    "Reels",
    "fragmovie",
    "campanhas publicitárias",
    "localização de vídeo",
    "narração com IA",
  ],
} as const;
